/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 d6.gltf 
Author: vojtaklemperer (https://sketchfab.com/vojtaklemperer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dice-low-and-high-poly-49e06b3cb50a4a6087f5f64cbb3566a3
Title: Dice (low and high poly)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/d6.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.dice_lowpoly_dice_lowpoly_0.geometry}
        material={materials.dice_lowpoly}
        position={[-0.601, 0.759, -1.694]}
        rotation={[-Math.PI / 2, 0, -0.391]}
        scale={100}
      />
      <mesh
        geometry={nodes.dice_hipoly_dice_hipoly_0.geometry}
        material={materials.dice_hipoly}
        position={[0.574, 0.759, 1.606]}
        rotation={[Math.PI / 2, 0, 0.391]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/d6.gltf");
